// src/decks.js

export const allDecks = [
  // Flashcard Decks
  { name: "General HR Questions", type: 'flashcard' },
  { name: "Behavioral Questions", type: 'flashcard' },
  { name: "JavaScript Fundamentals", type: 'flashcard' },
  { name: "Front-End Frameworks", type: 'flashcard' },
  { name: "Back-End Development", type: 'flashcard' },
  { name: "Searching & Sorting Algorithms", type: 'flashcard' },
  { name: "Data Structures (Advanced)", type: 'flashcard' },
  { name: "Python & Data Libraries", type: 'flashcard' },
  { name: "Statistics & Probability", type: 'flashcard' },
  { name: "Machine Learning Algorithms", type: 'flashcard' },
  { name: "Deep Learning", type: 'flashcard' },
  { name: "Version Control & Deployment", type: 'flashcard' },
  { name: "CI/CD Pipelines", type: 'flashcard' },
  { name: "Infrastructure as Code", type: 'flashcard' },
  { name: "Containerization & Orchestration", type: 'flashcard' },
  { name: "Cloud Platforms & Services", type: 'flashcard' },
  { name: "Network Security Fundamentals", type: 'flashcard' },
  { name: "Application Security (OWASP)", type: 'flashcard' },
  { name: "Cryptography Concepts", type: 'flashcard' },
  { name: "Ethical Hacking & Pen Testing", type: 'flashcard' },

  // Test Decks
  { name: "General HR Questions Test", type: 'test' },
  { name: "Behavioral Questions Test", type: 'test' },
  { name: "JavaScript Fundamentals Test", type: 'test' },
  { name: "Front-End Frameworks Test", type: 'test' },
  { name: "Back-End Development Test", type: 'test' },
  { name: "Searching & Sorting Algorithms Test", type: 'test' },
  { name: "Data Structures (Advanced) Test", type: 'test' },
  { name: "Python & Data Libraries Test", type: 'test' },
  { name: "Statistics & Probability Test", type: 'test' },
  { name: "Machine Learning Algorithms Test", type: 'test' },
  { name: "Deep Learning Test", type: 'test' },
  { name: "Version Control & Deployment Test", type: 'test' },
  { name: "CI/CD Pipelines Test", type: 'test' },
  { name: "Infrastructure as Code Test", type: 'test' },
  { name: "Containerization & Orchestration Test", type: 'test' },
  { name: "Cloud Platforms & Services Test", type: 'test' },
  { name: "Network Security Fundamentals Test", type: 'test' },
  { name: "Application Security (OWASP) Test", type: 'test' },
  { name: "Cryptography Concepts Test", type: 'test' },
  { name: "Ethical Hacking & Pen Testing Test", type: 'test' },
];